version: '3'

services:
  shortener:
    build: ./src
    image: lycantropos/shortener:latest
    entrypoint: /opt/shortener/docker-entrypoint.sh
    volumes:
      - ./src:/opt/shortener
    extra_hosts:
      - "dockerhost:$DOCKERHOST"  # for debugging
    ports:
      - 8000:8000
    environment:
      POSTGRES_URI: postgresql://username:password@postgres/shortener
      REDIS_URI: redis://redis:6379/1
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=shortener
    ports:
      - 5432:5432

  redis:
    image: redis:4

volumes:
  postgres_data:
