version: '3'

services:
  shortener:
    build: ./src
    image: lycantropos/shortener:latest
    entrypoint: /opt/shortener/docker-entrypoint.sh
    volumes:
      - ./src:/opt/shortener
    ports:
      - 8000:8000
    environment:
      REDIS_URI: redis://redis:6379/1

  redis:
    image: redis:4
